[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 11.0

[font.bold]
family = "FiraMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "FiraMonoNerdFont"
style = "BoldItalic"

[font.italic]
family = "FiraMonoNerdFont"
style = "Italic"

[font.normal]
family = "FiraMonoNerdFont"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000
multiplier = 3

[window]
dynamic_padding = true
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
